apiVersion: v1
kind: Service
metadata:
  name: pet-clinic-service
spec:
  selector:
    app: pet-clinic
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  externalIPs:
    - 192.168.50.11
